version: "3.2"
services:
  mongodb:
    image: mongo:4.4.13
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - $MONGODB_LOCAL_PORT:${MONGODB_DOCKER_PORT}
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    env_file: ./.env
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: mongodb
      DB_USER: ${MONGODB_USER}
      DB_PASSWORD: ${MONGODB_PASSWORD}
      DB_NAME: ${MONGODB_DATABASE}
      DB_PORT: ${MONGODB_DOCKER_PORT}
    stdin_open: true
    tty: true
volumes:
  db: